### ISSUE TITLE
lifecycle分支中提到app切回前台，前台指的是什么

### ISSUE THREAD

**Issue by sunskblue** [LightingContour/LC-JacocoSample#1]
1、lifecycle中在App切回前台时，切回前台指的是什么？
2、能否支持增量覆盖率统计

**Comment by LightingContour** [comment]
1.指的是把APP切换到后台（按下Home键/任务管理器中切其他APP之类的）后，再重新点开APP。这个时候会再统计一次覆盖率
2.Jacoco原生是没有增量覆盖率统计的，但是可以自己改造后面的部分实现。目前我没深入维护这个项目了，不过你可以这样试试：
 - Step1:将增量代码的部分自己单独记录下来
 - Step2:手工测试后，产出测试导出的jacoco报告，找增量代码是否在报告中覆盖率，然后自己输出一个仅增量代码的覆盖率报告

没收到通知才看到，见谅……我还以为没人对这项目感兴趣呢人(´･_･`)
